name: Cypress CI

on:
  push:
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório de testes
        uses: actions/checkout@v4

      - name: Checkout repositório da aplicação
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-heroes
          path: app

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalar dependências da aplicação
        run: |
          cd app
          npm install

      - name: Instalar dependências dos testes
        run: npm install

      - name: Rodar aplicação e testes
        run: npx start-server-and-test "cd app && npm start" http://localhost:3000 "npx cypress run"
