name: Cypress CI

on:
  push:
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório de testes
        uses: actions/checkout@v4

      - name: Checkout repositório da aplicação
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-heroes
          path: app

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências da aplicação
        run: |
          cd app
          npm install
          npm run setup

      - name: Subir aplicação
        run: |
          cd app
          npm run dev
      
      - name: Esperar aplicação subir
        run: npx wait-on http://localhost:3001

      - name: Instalar dependências dos testes
        run: npm install

      - name: Rodar testes Cypress
        run: npx cypress run
